batch_size: 128
<<<<<<< HEAD
epochs: 10
=======
epochs: 2
>>>>>>> fc66237 (baseline 1st try)
lr: 0.0002

device: cuda
num_workers: 4
seed: 1234
use_wandb: False

data_dir: /data1/akamaharuka/data-omni/

# Evaluation
model_path: 