batch_size: 256
epochs: 40
lr: 0.001

device: cuda:0
num_workers: 8
seed: 1234
use_wandb: False

data_dir: /content/drive/.shortcut-targets-by-id/1qxAFAKovUXm28TMQUFxKljs01WcTHCeY/ColabData/dl_lecture_competition_pub/data

# Evaluation
model_path: 
#model_path: outputs/model_best.pt