batch_size: 128
epochs: 80
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir_test: /kaggle/input/megdata-test/
data_dir_val: /kaggle/input/megdata-val/
data_dir_train: /kaggle/input/megdata-train/

# Evaluation
model_path: 