batch_size: 256
epochs: 100
lr: 0.001

device: cuda:0
num_workers: 8
seed: 1234
use_wandb: False

data_dir: data


# Model Hyperparameters
hid_dim: 128
num_blocks: 6  # 例: 畳み込みブロックの数
kernel_size: 5
lstm_hidden_dim: 64
lstm_layers: 3  # 例: LSTM層の数
dropout_prob: 0.5
weight_decay: 1e-5

# Evaluation
model_path: outputs/model_best.pt
